vk:
  #app data
  client-id: 5992417
  client-secret: cdVwYmloEM9v4p4bL43p
  api-version: 5.52
  #auth only
  display: page
  redirect-uri: http://localhost/doAuth
  scope: offline
  response-type: code
  #additional data
  default-period-to-seek: 10000
  max-query-size: 1000
  max-queries-per-second: 3

spring:
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/maryvk
    username: root
    password: root
server:
  port: 80
management:
  address: localhost
  port: 9001

---

spring:
  profiles: cloud
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-03.cleardb.net
    username: b0c5799c112ee6
    password: 7f2fc238
vk:
  redirect-uri: http://maryvk.cfapps.io/doAuth